name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]   # প্রতিদিন রাত 12টায় রান করবে
  workflow_dispatch:                # Manual run করার অপশন

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: sb-sagor
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Dhaka

          # Plugins
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_stars: yes
          plugin_achievements: yes
          plugin_lines: yes
          plugin_followup: yes
          plugin_people: yes
          plugin_repositories: yes

      - name: Commit Metrics to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add metrics.svg
          git commit -m "chore: update metrics"
          git push
