name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]   # প্রতিদিন রাত 12টায় রান করবে
  workflow_dispatch:                # Manual run করার অপশন

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: sb-sagor
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Dhaka
          extras: stars, achievements, lines
