name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]   # প্রতিদিন রাত 12টায় রান করবে
  workflow_dispatch:                # Manual run করার অপশন

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: sb-sagor

          # Base card
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Dhaka

          # Plugins
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_stars: yes
          plugin_achievements: yes
          plugin_lines: yes
          plugin_followup: yes
          plugin_people: yes
          plugin_repositories: yes

          # Output settings
          filename: metrics.svg
          output_action: commit
          committer_branch: main            # master হলে master লিখবে
          committer_message: "chore: update metrics"
